name: qr_code
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  qr_flutter: ^4.1.0
  image_picker: ^1.1.2
  bloc: ^8.1.4
  qr_code_scanner: ^1.0.1
  flutter_barcode_scanner: ^2.0.0
  flutter_launcher_icons: ^0.13.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/

flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/images/image.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/images/image.png"
